configs:
  # auto-tag
  - id: environment-tag
    type:
      api: auto-tag
    config:
      name: environment
      template: auto-tag.json
      parameters:
        dynamicKey: KUBERNETES_NAMESPACE
        valueFormat: "{ProcessGroup:KubernetesNamespace}"
      skip: false
  
  - id: app-tag
    type:
      api: auto-tag 
    config:
      name: app
      template: auto-tag.json
      parameters:
        dynamicKey: KUBERNETES_CONTAINER_NAME
        valueFormat: "{ProcessGroup:KubernetesContainerName}"
      skip: false


  # request-attribute
  - id: ltn-request-attribute
    type:
      api: request-attributes
    config:
      name: LTN
      template: request-attribute.json
      parameters:
        delimiter: LTN=
        endDelimiter: ;
        headerName: x-dynatrace-test
      skip: false
  
  - id: tsn-request-attribute
    type:
      api: request-attributes
    config:
      name: TSN
      template: request-attribute.json
      parameters:
        delimiter: TSN=
        endDelimiter: ;
        headerName: x-dynatrace-test
      skip: false
  
  - id: lsn-request-attribute
    type:
      api: request-attributes
    config:
      name: LSN
      template: request-attribute.json
      parameters:
        delimiter: LSN=
        endDelimiter: ;
        headerName: x-dynatrace-test
      skip: false

