configs:
  # application-web 
  - id: application
    config:
      name:
        type: compound
        format: "{{ .appName }} - {{ .appEnvironment }}"
        references:
          - appName
          - appEnvironment
      template: application.json
      parameters:
        appName:
          name: TEMPLATE_APP_NAME
          type: environment
        appEnvironment:
          name: TEMPLATE_APP_ENVIRONMENT
          type: environment
    type:
      api: application-web

  # app-detection-rule
  - id: application-detection-rule
    config:
      name:
        configType: application-web
        configId: application
        property: name
        type: reference
      template: application-detection-rule.json
      parameters:
        applicationId:
          configType: application-web
          configId: application
          property: id
          type: reference
        pattern:
          name: TEMPLATE_APP_URL_PATTERN
          type: environment
    type:
      api: app-detection-rule
  
  # management-zone
  - id: management-zone
    config:
      name:
        name: TEMPLATE_K8S_NAMESPACE
        type: environment
      parameters:
        environment:
          name: TEMPLATE_K8S_NAMESPACE
          type: environment
      template: management-zone.json
      skip: false
    type:
      api: management-zone

  # dashboard
  - id: dashboard
    config:
      name:
        name: TEMPLATE_APP_NAME
        type: environment
      parameters:
        managementZoneId:
          configType: management-zone
          configId: management-zone
          property: id
          type: reference
        managementZoneName:
          configType: management-zone
          configId: management-zone
          property: name
          type: reference
      template: dashboard.json
      skip: false
    type:
      api: dashboard

  # synthetic-location
  - id: synthetic-location
    config:
      name: ACE-BOX
      parameters:
        nodeId:
          name: SYNTH_NODE_ID
          type: environment
      template: private-synthetic-location.json
      skip: false
    type:
      api: synthetic-location
  
  # synthetic-monitor
  - id: health-check
    config:
      name:
        type: compound
        format: "{{ .appName }} health-check"
        references:
          - appName
      parameters:
        appName:
          name: TEMPLATE_APP_NAME
          type: environment
        description:
          type: compound
          format: "Health check for {{ .appName }}"
          references:
            - appName
        location:
          configType: synthetic-location
          configId: synthetic-location
          property: id
          type: reference
        tag:
          name: TEMPLATE_K8S_NAMESPACE
          type: environment
        url:
          name: TEMPLATE_HEALTH_CHECK_URL
          type: environment
        managementZoneId:
          configType: management-zone
          configId: management-zone
          property: id
          type: reference
      template: health-check-monitor.json
    type:
      api: synthetic-monitor
