configs:
- id: simplenode.staging
  type:
    api: calculated-metrics-service
  config:
    name: simplenode.staging
    template: csm.json
    parameters:
      metricKey: calc:service.simplenode.staging
    skip: false

